version: "3.3"

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"  # <-- Gán port 80 thật
    container_name: react_nginx_app
    restart: always